### ISSUE TITLE
Datapack Support for Various Eidolon Recipe Types

### ISSUE THREAD

**Issue by Bobisnotap** [elucent/eidolon#66] opened 2021-02-13 21:45 UTC
It seems that currently we cannot add any new recipes via datapack to any of the crafting systems Eidolon supplies, like the Magic Workbench Crafting or the Crucible's Alchemy.

Would this be possible in a future version of a mod?
This would be super useful for modpack makers.

**Comment by elucent** [comment] 2021-02-20 21:46
Duplicate of #19. It's implemented locally for some recipe types but it's very time-consuming and tedious switching everything over.

**Closed by elucent** 2021-02-20 21:46 UTC
Labels: duplicate
