### ISSUE TITLE
[Compatibility Issue?] Crash when trying to generate catacombs with terraforged

### ISSUE THREAD

**Issue by Corvus20** [elucent/eidolon#44] opened 2021-01-19 18:09 UTC
**Describe the bug**
The game crashed entirely, and according to the crash logs, a critical error occurred when Terraforged was trying to generate Eidolon's catacombs.

**To Reproduce**
I was just loading new chunks in a creative world, to test for issues in my personal modpack. Apparently there were issues. Load a Terraforged world and load chunks until it tries to generate a catacombs structure.

**Environment**
I am currently using Eidolon 0.2.7, and I am on a single player world.

**Crash Report**
[crash-2021-01-19_12.58.26-client.txt](https://github.com/elucent/eidolon/files/5837737/crash-2021-01-19_12.58.26-client.txt)

Note: These mods did not clash in the past with each other, or any other mod in my modpack for that matter. It is likely an issue with the newest version of either Eidolon or Terraforged.

**Comment by elucent** [comment] 2021-01-21 20:34
Based on the crash report sent in the Eidolon discord, this appears to be caused by this issue: https://github.com/Melonslise/Subterranean-Wilderness/issues/18. I'll close this when that issue is resolved, but please reopen if the error persists afterwards.

**Closed** 2021-02-02 20:09 UTC
Labels: bug
