### ISSUE TITLE
Magic Workbench capable of mass duping items easily.

### ISSUE THREAD

**Issue by Krakatoah** [elucent/eidolon#101] opened 2021-06-13 14:42 UTC
If you craft any item inside the magic workbench whilst having a stack of 3+ items in any of the auxillary slots, the items in the auxillary slots will be doubled, even past the normal stack limit for that item.

In the example screenshots, I used the bug to duplicate clay in vast quantities, I burnt the clay with lava afterward.
![2021-06-13_15 38 10](https://user-images.githubusercontent.com/13937436/121811817-7c0a3280-cc5d-11eb-9434-308041a42185.png)
![2021-06-13_15 38 13](https://user-images.githubusercontent.com/13937436/121811824-7f052300-cc5d-11eb-832f-878c5ed11a0b.png)
![2021-06-13_15 38 14](https://user-images.githubusercontent.com/13937436/121811826-7f9db980-cc5d-11eb-95af-061e08754b6a.png)
![2021-06-13_15 38 16](https://user-images.githubusercontent.com/13937436/121811827-80365000-cc5d-11eb-98d0-f34458fa4093.png)
![2021-06-13_15 38 17](https://user-images.githubusercontent.com/13937436/121811831-82001380-cc5d-11eb-8ae6-8c8fe0937642.png)
![2021-06-13_15 38 19](https://user-images.githubusercontent.com/13937436/121811834-83c9d700-cc5d-11eb-9051-e1de2b506f7b.png)

**Comment by Codethulhu03** [comment] 2021-07-29 14:29
Seems like this happens with any recipe not registered by eidolon and most items in the auxiliary slots, I'd guess it's an issue in gui/WorktableResultSlot#onTake (around Line 101) 
- My Guess: Any item not registered for the auxiliary slots in a recipe will grow by it's own amount

**Comment by elucent** [comment] 2021-12-16 19:26
Duplicate of #57.

**Closed by elucent** 2021-12-16 19:26 UTC
