### ISSUE TITLE
Ritual of Purifying freezes game.

### ISSUE THREAD

**Issue by Moomallowz** [elucent/eidolon#20] opened 2020-12-29 03:57 UTC
**Description**
The Ritual of Purifying froze the game when I performed it, and upon restarting the game, the nearby zombie villagers had not been reverted. I was able to replicate this multiple times.

**To Reproduce**
The ritual was performed in Creative Mode.

**Environment**
I was playing in a singleplayer 1.16.4 world, with eidolon-0.2.4 installed.

**Crash Report**
Was unable to recover a crash report, as the game had to be forcequit in Task Manager.

**Comment by elucent** [comment] 2020-12-29 23:50
Are you running with any other mods? I can't replicate this locally, in singleplayer or multiplayer. I'm just performing the ritual with some zombie villagers nearby, and they are all successfully cured.

Could you post a modlist, if running with multiple mods, and also maybe some screenshots or more detailed information on what you did?

**Comment by elucent** [comment] 2020-12-29 23:50
Didn't mean to close, this is still a bug. :p

**Comment by Moleculor** [comment] 2020-12-30 16:49
I saw this Issue and decided to try and test it to see what I might discover. Was able to reproduce. Note that this is Forge 35.1.28.

1. Install Forge, Minecraft.
2. Create a new, creative world. 
3. `/locate village` and teleport to it.
4. Set the time to night.
5. Turn off DaylightCycle
6. Build a fenced in area about 7x7 somewhere near the village but not necessarily inside it.
7. Spawn two dozen zombie villagers inside this area.
8. Perform the relevant ritual.

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/30/20, 10:46 AM
Description: Ticking block entity

java.lang.ClassCastException: class net.minecraft.entity.monster.ZombieVillagerEntity cannot be cast to class elucent.eidolon.mixin.ZombieVillagerEntityMixin (net.minecraft.entity.monster.ZombieVillagerEntity and elucent.eidolon.mixin.ZombieVillagerEntityMixin are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @50f40653)
at elucent.eidolon.ritual.PurifyRitual.start(PurifyRitual.java:45) ~[eidolon:0.2.4] {re:classloading}
at elucent.eidolon.tile.BrazierTileEntity.func_73660_a(BrazierTileEntity.java:187) ~[eidolon:0.2.4] {re:classloading}
at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:classloading}
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
at java.lang.Thread.run(Thread.java:832) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
at elucent.eidolon.ritual.PurifyRitual.start(PurifyRitual.java:45) ~[eidolon:0.2.4] {re:classloading}
at elucent.eidolon.tile.BrazierTileEntity.func_73660_a(BrazierTileEntity.java:187) ~[eidolon:0.2.4] {re:classloading}
-- Block entity being ticked --
Details:
Name: eidolon:brazier_tile // elucent.eidolon.tile.BrazierTileEntity
Block: Block{eidolon:brazier}
Block location: World: (233,68,-119), Chunk: (at 9,4,9 in 14,-8; contains blocks 224,0,-128 to 239,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Block: Block{eidolon:brazier}
Block location: World: (233,68,-119), Chunk: (at 9,4,9 in 14,-8; contains blocks 224,0,-128 to 239,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:classloading}


-- Affected level --
Details:
All players: 1 total; [ServerPlayerEntity['Moleculor'/204, l='ServerLevel[New World]', x=229.00, y=69.91, z=-119.46]]
Chunk stats: ServerChunkCache: 2947
Level dimension: minecraft:overworld
Level spawn location: World: (30,63,-11), Chunk: (at 14,3,5 in 1,-1; contains blocks 16,0,-16 to 31,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Level time: 3190 game time, 13095 day time
Level name: New World
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Level weather: Rain time: 28099 (now: false), thunder time: 98138 (now: false)
Known server brands: forge
Level was modded: true
Level storage version: 0x04ABD - Anvil
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
at java.lang.Thread.run(Thread.java:832) [?:?] {}


-- System Details --
Details:
Minecraft Version: 1.16.4
Minecraft Version ID: 1.16.4
Operating System: Windows 10 (amd64) version 10.0
Java Version: 14.0.2, AdoptOpenJDK
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
Memory: 6177843712 bytes (5891 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
CPUs: 8
JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
ModLauncher: 8.0.6+85+master.325de55
ModLauncher launch target: fmlclient
ModLauncher naming: srg
ModLauncher services: 
/mixin-0.8.2.jar mixin PLUGINSERVICE 
/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
/forge-1.16.4-35.1.28.jar object_holder_definalize PLUGINSERVICE 
/forge-1.16.4-35.1.28.jar runtime_enum_extender PLUGINSERVICE 
/forge-1.16.4-35.1.28.jar capability_inject_definalize PLUGINSERVICE 
/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
/forge-1.16.4-35.1.28.jar runtimedistcleaner PLUGINSERVICE 
/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
/forge-1.16.4-35.1.28.jar fml TRANSFORMATIONSERVICE 
FML: 35.1
Forge: net.minecraftforge:35.1.28
FML Language Providers: 
javafml@35.1
minecraft@1
Mod List: 
forge-1.16.4-35.1.28-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
forge-1.16.4-35.1.28-universal.jar                |Forge                         |forge                         |35.1.28             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
jeiintegration_1.16.4-6.1.1.11.jar                |JEI Integration               |jeiintegration                |6.1.1.11            |DONE      |NOSIGNATURE
curios-forge-1.16.4-4.0.3.0.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.0      |DONE      |NOSIGNATURE
eidolon-0.2.4.jar                                 |Eidolon                       |eidolon                       |0.2.4               |DONE      |NOSIGNATURE
jei-1.16.4-7.6.0.62.jar                           |Just Enough Items             |jei                           |7.6.0.62            |DONE      |NOSIGNATURE
Crash Report UUID: 46e112e3-2ee8-4f95-97b0-42f2a1ca5e77
Player Count: 1 / 8; [ServerPlayerEntity['Moleculor'/204, l='ServerLevel[New World]', x=229.00, y=69.91, z=-119.46]]
Data Packs: vanilla, mod:forge, mod:jeiintegration, mod:curios, mod:eidolon, mod:jei
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'forge'
```

**Comment by elucent** [comment] 2020-12-30 18:58
I'll try updating my local forge and see if it persists. It looks like the mixin is just not getting applied, which is strange.

**Comment by elucent** [comment] 2020-12-30 19:21
Oh, I might've just been building my mixin wrong. So it would work in my local version, but not in the jar. I think this should be fixed in the next update.

**Closed** 2021-01-03 19:49 UTC
Labels: bug
